[versions]
kotlin = "1.5.10"
android-gradlePlugin = "7.1.0-alpha02"
google-services-gradlePlugin = "4.3.8"
dependencyUpdatesPlugin = "0.39.0"
compose = "1.0.0-beta09"
androidx-activity = "1.3.0-beta02"
androidx-navigation = "2.4.0-alpha03"
androidx-lifecycle = "2.4.0-alpha02"
accompanist = "0.12.0"
datastore = "1.0.0-beta02"
ktor = "1.6.0"
exoplayer = "2.14.1"
youtubeExtractor = "master-SNAPSHOT"
junit = "4.13.2"
androidx-test = "1.1.2"
espresso = "3.3.0"
logback = "1.2.3"
coroutines = "1.5.0-native-mt"
koin = "3.0.2"
settings = "0.7.7"
firebase-dynamicLinks = "20.1.0"
paging-compose = "1.0.0-alpha10"
paging-multiplatform = "0.4.2"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
google-services-gradlePlugin = { module = "com.google.gms:google-services", version.ref = "google-services-gradlePlugin" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
datastore-runtime = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
youtubeExtractor = { module = "com.github.HaarigerHarald:android-youtubeExtractor", version.ref = "youtubeExtractor" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings" }
settingscoroutines = { module = "com.russhwolf:multiplatform-settings-coroutines-native-mt", version.ref = "settings" }
settingsdatastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }
firebase-dynamicLinks = { module = "com.google.firebase:firebase-dynamic-links-ktx", version.ref = "firebase-dynamicLinks" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
paging-multiplatform = { module = "io.github.kuuuurt:multiplatform-paging", version.ref = "paging-multiplatform" }

[bundles]
compose = ["compose-ui", "compose-tooling", "compose-material", "compose-runtime"]
ktor = ["ktor-core", "ktor-android", "ktor-serialization", "ktor-logging"]
accompanist = ["accompanist-coil", "accompanist-insets", "accompanist-flowlayout"]
koin = ["koin-android", "koin-core"]
