[versions]
kotlin = "1.4.31"
compose = "1.0.0-beta02"
androidx-activity = "1.3.0-alpha04"
androidx-navigation = "1.0.0-alpha09"
acompanist = "0.6.2"
datastore = "1.0.0-alpha08"
lottie = "1.0.0-alpha07-SNAPSHOT"
ktor = "1.5.2"
jsoup = "1.13.1"
mavericks = "2.1.0-alpha01"
exoplayer = "2.13.2"
youtubeExtractor = "v2.1.0"
junit = "4.13.2"
androidx-test = "1.1.2"
espresso = "3.3.0"
logback = "1.2.3"
coroutines = { strictly = "1.4.2-native-mt" }
koin = "3.0.1-beta-1"
settings = "0.7.4"
koru = "0.3.4"

[libraries]
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
accompanist-coil = { module = "dev.chrisbanes.accompanist:accompanist-coil", version.ref = "acompanist" }
accompanist-insets = { module = "dev.chrisbanes.accompanist:accompanist-insets", version.ref = "acompanist" }
datastore-runtime = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
mavericks-compose = { module = "com.airbnb.android:mavericks-compose", version.ref = "mavericks" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer", exclude = "com.google.android.exoplayer:exoplayer-ui" }
youtubeExtractor = { module = "com.github.HaarigerHarald:android-youtubeExtractor", version.ref = "youtubeExtractor" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settingscoroutines = { module = "com.russhwolf:multiplatform-settings-coroutines-native-mt", version.ref = "settings" }
settingsdatastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }
koru = { module = "com.futuremind:koru", version.ref = "koru" }

[bundles]
compose = ["compose-ui", "compose-tooling", "compose-material"]