[versions]
android-minSdk = "28"
android-targetSdk = "31"
android-compileSdk = "31"
kotlin = "1.5.21"
android-gradlePlugin = "7.1.0-alpha08"
google-services-gradlePlugin = "4.3.10"
dependencyUpdatesPlugin = "0.39.0"

androidx-compose = "1.0.1"
androidx-activity = "1.3.1"
androidx-navigation = "2.4.0-alpha07"
androidx-lifecycle = "2.4.0-alpha03"
androidx-datastore = "1.0.0"
androidx-espresso = "3.3.0"
androidx-core-splashscreen = "1.0.0-alpha01"
androidx-constraintlayout-compose = "1.0.0-beta02"

accompanist = "0.17.0"
ktor = "1.6.2"
exoplayer = "2.15.0"
youtubeExtractor = "master-SNAPSHOT"
junit = "4.13.2"
androidx-test = "1.1.2"
logback = "1.2.3"
coroutines = "1.5.1-native-mt"
koin = "3.1.2"
multiplatformsettings = "0.7.7"
firebase-dynamicLinks = "20.1.1"
paging-compose = "1.0.0-alpha12"
multiplatformpaging = "0.4.2"
coil = "1.3.2"

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependencyUpdates = { id = "com.github.ben-manes.versions", version = "0.39.0" }

[libraries]
#Plugins
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }
google-services-gradlePluginClasspath = { module = "com.google.gms:google-services", version.ref = "google-services-gradlePlugin" }

#AndroidX
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-datastore-runtime = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test" }

#Accompanist
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }

#Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

#Testing
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
junit = { module = "junit:junit", version.ref = "junit" }

#Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#Multiplatform settings
multiplatformsettings-noarg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformsettings" }
multiplatformsettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines-native-mt", version.ref = "multiplatformsettings" }
multiplatformsettings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformsettings" }

#Others
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
youtubeExtractor = { module = "com.github.HaarigerHarald:android-youtubeExtractor", version.ref = "youtubeExtractor" }
firebase-dynamicLinks = { module = "com.google.firebase:firebase-dynamic-links-ktx", version.ref = "firebase-dynamicLinks" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
multiplatformpaging = { module = "io.github.kuuuurt:multiplatform-paging", version.ref = "multiplatformpaging" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[bundles]
androidx-compose = ["androidx-compose-ui", "androidx-compose-tooling", "androidx-compose-material", "androidx-compose-runtime"]
ktor = ["ktor-core", "ktor-android", "ktor-serialization", "ktor-logging"]
accompanist = ["accompanist-insets", "accompanist-flowlayout", "accompanist-navigation-material", "accompanist-navigation-animation"]
koin = ["koin-android", "koin-core", "koin-compose"]
