name: Android CI

on:
  push:
    branches:
      - master
    tags:
      - v**
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ANDROID_RELEASE_KEYSTORE_PWD: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PWD }}
      ANDROID_RELEASE_KEY_PWD: ${{ secrets.ANDROID_RELEASE_KEY_PWD }}
      OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build number
        shell: bash
        run: echo "BUILD_NUMBER=$(expr $GITHUB_RUN_NUMBER + 5210)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Make checksum executable
        run: chmod +x .github/checksum.sh

      - name: Generate cache key
        run: .github/checksum.sh checksum.txt

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: actions/cache@v2
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Detekt all
        uses: natiginfo/action-detekt-all@1.23.0
        with:
          args: --config .github/detekt.yml --report sarif:./reports/detekt.sarif

      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v1.1.5
        if: always()
        with:
          sarif_file: ./reports/detekt.sarif
          sha: ${{ env.GITHUB_SHA }}
          ref: ${{ env.GITHUB_REF }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease bundleRelease -Pbarnee.versioncode=$BUILD_NUMBER --scan --stacktrace

      - name: Generate changellog
        id: generate-release-changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true"
          stripHeaders: "true"
          stripGeneratorNotice: "true"

      - name: Create release for tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
          body: ${{ steps.generate-release-changelog.outputs.changelog }}

      - name: Publish to Play store
        if: startsWith(github.ref, 'refs/tags/v')
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_ACCOUNT_JSON }}
          packageName: com.popalay.barnee
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: app/build/outputs
